[package]
name = "rcom"
version = "0.0.8"
edition = "2021"
repository = "https://github.com/accelerant-dev/implement-rougedb"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
